# Generated by Django 4.1.4 on 2022-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_blogtitle_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='fname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='lname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
